spring:
  application:
    name: layered
  datasource:
    url: jdbc:postgresql://localhost:5432/architecture-service
    username: architecture-service
    password: d4nc31ng0nR41nb0w5
    driverClassName: org.postgresql.Driver
  sql:
    init:
      mode: always
  kafka:
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      key-deserializer: org.springframework.kafka.support.serializer.ParseStringDeserializer
