name: Build Test Suites

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - services/test-suites/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version-file: services/toolchains/.java-version

      - uses: gradle/actions/setup-gradle@v3

      - run: ./gradlew :services:test-suites:check --no-daemon
