---
name: "Build Base"
"on":
  workflow_dispatch: null
  push:
    branches:
    - "main"
    paths:
    - "services/base/**"
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v5"
    - uses: "actions/setup-java@v4"
      with:
        distribution: "temurin"
        java-version: 21
    - run: "./gradlew :services:base:check --no-daemon"
