---
name: "Build Toolchains"
"on":
  workflow_dispatch: null
  push:
    branches:
    - "main"
    paths:
    - "services/toolchains/**"
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v4"
    - uses: "actions/setup-java@v4"
      with:
        distribution: "temurin"
        java-version-file: "services/toolchains/.java-version"
    - uses: "gradle/actions/setup-gradle@v4"
    - run: "./gradlew :services:toolchains:check --no-daemon"
