name: Build Base

on:
  push:
    branches:
      - main
    paths:
      - services/base/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          overwrite-settings: false

      - run: ./gradlew check --no-daemon
        working-directory: services/base
