---
name: "Submit Dependencies"
"on":
  workflow_dispatch: null
  schedule:
  - cron: "0 9 * * 1-5"
  push:
    branches:
    - "main"
    paths:
    - "**/build.gradle.kts"
jobs:
  build:
    permissions:
      contents: "write"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v5"
    - uses: "actions/setup-java@v5"
      with:
        distribution: "temurin"
        java-version-file: "services/toolchains/.java-version"
    - uses: "gradle/actions/dependency-submission@v4"
