name: Submit Dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1-5"
  push:
    branches:
      - main
    paths:
      - "**/build.gradle.kts"

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          overwrite-settings: false

      - uses: gradle/actions/dependency-submission@v3
